name: NemisysSlotChange
main: NemisysSlotChange.MainClass
version: "1.0.0"
api: ["1.0.0"]
author: XFuryMCPE
description: Change nemisys slots to one over the total amount
website: https://twitter.com/xfurymcpe
